### ISSUE TITLE
JSONDecodeError upon deleting users.

### ISSUE THREAD

**Issue by TantumNTatari** [samamorgan/helpjuice#10]
Hi, I've noticed that I get this error when I delete users from Helpjuice using the wrapper. I'm guessing that there is actually no JSON object returned from a successful deletion (the user is gone when I check the actual platform, and directly using the API to delete gives me a 200 response).

I wonder if it's the same thing with other resources? 

Thanks.

**Comment by samamorgan** [comment]
I suspect I know what's going on, but can you give a full traceback of the error?

Suspicion: Helpjuice changed the delete response from an empty object `{}` to no content.

**Comment by samamorgan** [comment]
Closing (stale)
