### ISSUE TITLE
Search activities missing

### ISSUE THREAD

**Issue by pmaranin** [samamorgan/helpjuice#13]
Hi Sam,

is there a chance you could add to the wrapper the [history of search activities](https://help.helpjuice.com/en_US/API/retrieving-searches-throught-api) that is provided by the v2 API  my_account.helpjuice.com/api/searches ?

That would be a super useful addition !

Thx

**Comment by samamorgan** [comment]
This wrapper is for API v3. Unfortunately, the implementers at Helpjuice have not ported that functionality to the new API from what I can tell.

**Comment by pmaranin** [comment]
Thanks for the prompt answer.

Yep, I have reached out to them and they have no immediate plan unfortunately to move it to v3.
As you had the API version as a parameter in your wrapper, I thought you were able to perform v2 calls.
I'm not sure how hard it would be to integrate it in your wrapper . This is what I am using as a workaround in the meantime

```
HELPJUICE_BASE_URL = 'https://xxxxx.helpjuice.com/api/searches.csv'
payload = {
'api_key': 'API_KEY',
'limit': 5000,
'page': 1,
}
response = requests. Get(HELPJUICE_BASE_URL, params=payload)
if response.status_code not in range(200,300):
    print(response.status_code)
else:
    results = list(csv.DictReader(StringIO(response. Text)))
```
